### PR TITLE
feat: add camunda exporter support to zeebe 

### PR DESCRIPTION
**Pull request by drodriguez-305**
### Which problem does the PR fix?
Related to https://github.com/camunda/camunda-platform-helm/issues/2294

### What's in this PR?
Adding support for the new camunda exporter.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/docs/contributing.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/docs/contributing.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
@drodriguez-305 LGTM :+1: 
Just let's check why the deployment failed.

**Comment by drodriguez-305** [comment]
@aabouzaid at first we noticed that the url was added with an extra line. After fixing the url template rendering issue, I am still encountering getting an error in zeebe.
```
│ 2024-10-17 21:03:55.691 [Broker-0] [zb-fs-workers-2] [Exporter-1] ERROR                                                                                                                 │
│       io.camunda.zeebe.broker.exporter - Failed to open exporter 'CamundaExporter'. Retrying...                                                                                         │
│ java.lang.IllegalArgumentException: HTTP Host may not be null
```

Confirmed by checking the configmap and it seems to be rendering the url correctly into the camunda exporter.
```
Name:         integration-zeebe-configuration
Namespace:    camunda-pr-2476-intg-alpha
Labels:       app=camunda-platform
              app.kubernetes.io/component=zeebe-broker
              app.kubernetes.io/instance=integration
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=camunda-platform
              app.kubernetes.io/part-of=camunda-platform
              app.kubernetes.io/version=8.6.0
              helm.sh/chart=camunda-platform-0.0.0-ci-snapshot-alpha
Annotations:  meta.helm.sh/release-name: integration
              meta.helm.sh/release-namespace: camunda-pr-2476-intg-alpha

Data
====
startup.sh:
----
#!/usr/bin/env bash
set -eux -o pipefail
export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-$[${K8S_NAME##*-} * 1 + 0]}

if [ "$(ls -A /exporters/)" ]; then
  mkdir -p /usr/local/zeebe/exporters/
  cp -a /exporters/*.jar /usr/local/zeebe/exporters/
else
  echo "No exporters available."
fi
exec /usr/local/zeebe/bin/broker

application.yaml:
----
zeebe:
  broker:
    exporters:
      elasticsearch:
        className: "io.camunda.zeebe.exporter.ElasticsearchExporter"
        args:
          url: "http://integration-elasticsearch:9200"
          index:
            prefix: "zeebe-record"
      CamundaExporter:
        className: "io.camunda.exporter.CamundaExporter"
        args:
          connect:
            type: elasticsearch
            url: "http://integration-elasticsearch:9200"
          index:
            prefix: "zeebe-record"
          createSchema: true
    gateway:
      enable: true
      network:
        port: 26500
      security:
        enabled: false
        authentication:
          mode: none
    network:
      host: 0.0.0.0
      commandApi:
        port: 26501
      internalApi:
        port: 26502
      monitoringApi:
        port: "9600"
    cluster:
      clusterSize: "3"
      replicationFactor: "3"
      partitionsCount: "3"
      clusterName: integration-zeebe
    threads:
      cpuThreadCount: "3"
      ioThreadCount: "3"

# Camunda Database configuration
camunda.database:
  type: elasticsearch
  # Cluster name
  clusterName: elasticsearch
  # Elasticsearch full url
  url: "http://integration-elasticsearch:9200"

broker-log4j2.xml:
----


BinaryData
====

Events:  <none>
```

**Comment by mustafadagher** [comment]
> @mustafadagher can you confirm if there is anything that might be missing?

@drodriguez-305 to me, the configuration you posted looks correct. but I'm not sure if there might be wrong indentation or something that causes the url not to be read!

**Review by aabouzaid — APPROVED** [review]
LGTM, let's just wait for the CI to finish before we merge.

**Pull request merged**
