### PR TITLE
feat: adding openshift routes

### PR DESCRIPTION
**Pull request by hamza-m-masood**
### What's in this PR?

Rleated: https://github.com/camunda/distribution/issues/254
### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] In the repo's root dir, run `make go.update-golden-only`.
- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by hamza-m-masood** [comment]
To start out, I will add a global flag to enabled routes for each components.
The first route object I will create will be fore identity.

**Comment by hamza-m-masood** [comment]
Not sure if `ingress.kubernetes.io/rewrite-target: /` is needed as an annotation.

**Comment by hamza-m-masood** [comment]
I am now able to get identity working with it's route object and no tls

**Comment by hamza-m-masood** [comment]
@aabouzaid How should I implement the tls secret functionality?
openshift routes define the tls certificate and key inside the route itself and do not reference any secret.
Knowing this, how should I structure the values.yaml?

The easiest way would be as follows:
```
identity:
  routes:
    tls:
      enabled: false
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
      certificate: ""
      key: ""

```
Give the customer the option to specify the raw certificate and key in the values.yaml.

Another option (but a little tricky to implement) would be to reference an already existing k8s secret in the values.yaml:
```
identity:
  routes:
    tls:
      enabled: false
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
      existingSecret: testSecret
```
The route object template would have to extract the information from the existing k8s secret. I am not completely sure how this would be done but I can work my way through this.

The final option I see is to not give the option to specify a tls cert and key in the values.yaml. If the customer really want a tls in their routes then we can tell them to generate the routes through the ingress because the ingress generated routes automatically includes the tls contents from the secret that the ingress references. 

The customer could also manually add in the tls contents in each route themselves.

**Comment by hamza-m-masood** [comment]
Thank you @leiicamundi that really helped. So I will go with the option of the customer defining the `existingSecret` key in the values.yaml.

**Comment by hamza-m-masood** [comment]
I wanted to stay away from using the lookup function because of the dependency on the kubernetes API. This dependency can introduce potential points of failure, especially if the API server is experiencing issues or is not accessible. 

Also using helm commands like `helm template` won't give the correct output if the lookup function is used.

I will still implement it since you guys approve of it, and I will test it out myself to see how reliable it is.

**Comment by hamza-m-masood** [comment]
@jessesimpson36's reponse to the above:
I'm personally fine with making users specify their certificate in values.yaml, since users have to do that anyway in the Route api.  I dislike lookUp for the reasons you gave in github.  But I think your judgement   will be most valuable here.
If you wanted to implement your own lookUp, I can show you how I added a keyword into a custom build of helm. it could help you debug or further understand the existing implementation of lookUp.

**Comment by hamza-m-masood** [comment]
I hope it is clear from my comment but I agree with Jesse. I think it's okay to specify the tls cert and key in the values.yaml. 
I'm just a bit hesitant because I don't know what our customers would think about that. 
Maybe we can have both options?
1. Defining the tls crt and key in the values.yaml
2. Defining an existingSecret

**Comment by jessesimpson36** [comment]
But if you can make `existingSecret` work, that'd be pretty sweet too!

**Comment by hamza-m-masood** [comment]
@jessesimpson36 
I personally am not very comfortable in telling the customer to manually modify their helm installation after successful deployment because of multiple reasons: configuration drift, loss of idempotency (meaning running a helm install on the same values.yaml is not going to give the same result, making future helm operations unpredictable), upgrade and rollback problems, inconsistencies across environments, problems with CI/CD (maybe customers will have to modify their pipelines to add this extra manual step)

**Comment by hamza-m-masood** [comment]
Thanks @leiicamundi that really helps.

**Comment by hamza-m-masood** [comment]
Closing this PR since we agreed to generate the routes from ingress objects.

**Pull request closed without merging**
