### PR TITLE
feat: configure Webapps with REST v2 Api

### PR DESCRIPTION
**Pull request by Zelldon**
### Which problem does the PR fix?

 * The newest version of Camunda/Operate and Tasklist (8.6) will start the Camunda REST API locally (to reduce an extra hop to the gateway) and send commands
       to Zeebe. The respecitive component will join the atomix (SWIM) cluster. This is to retrieve the topology of the Zeebe cluster, being able to use the Broker client correctly
 * To join the atomix cluster, we have to configure certain properties like cluster name, member id, port, etc.
 * These env vars are not problematic for earlier versions, as they are ignored in this case.

See the related PR that makes this refactoring and the gateway-rest API available for all components https://github.com/camunda/camunda/pull/1919

### What's in this PR?

This PR adds some new values to configure a new port of the Operate deployment. Furthermore, it adds new environment variables to the deployment, such that we can join the related Zeebe cluster (via SWIM).

#### Test

I tested the changes together with the changes of:

* https://github.com/camunda/camunda-platform-helm/pull/1660
* https://github.com/camunda/camunda-platform-helm/pull/1672
* https://github.com/camunda/camunda-platform-helm/pull/1647

I used the following extra values file:

```
$ cat values-patch.yaml 
global:
  identity:
    auth:
      enabled: false

operate:
  image:
     ## @param operate.image.registry can be used to set container image registry.
     registry: "gcr.io"
     ## @param operate.image.repository defines which image repository to use
     repository: zeebe-io/operate
     ## @param operate.image.tag can be set to overwrite the global tag, which should be used in that chart
     tag: ck-rs-dist-shared-modules-rest

identityKeycloak:
  enabled: false
tasklist:
  enabled: false
optimize:
  enabled: false
identity:
  enabled: false
connectors:
  enabled: false

```

Deployment in zeebe-io via `helm install camunda-platform-test charts/camunda-platform -f values-patch.yaml`

Running the following:
```
$ curl -c cookie.txt -X POST 'http://localhost:8080/api/login?username=demo&password=demo'
$ curl -b cookie.txt -X GET 'http://localhost:8080/v2/topology'  | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1023    0  1023    0     0  13460      0 --:--:-- --:--:-- --:--:-- 13640
{
  "brokers": [
    {
      "nodeId": 0,
      "host": "camunda-platform-test-zeebe-0.camunda-platform-test-zeebe.ck-test-helm.svc",
      "port": 26501,
      "partitions": [
        {
          "partitionId": 1,
          "role": "leader",
          "health": "healthy"
        },
        {
          "partitionId": 3,
          "role": "follower",
          "health": "healthy"
        },
        {
          "partitionId": 2,
          "role": "follower",
          "health": "healthy"
        }
      ],
      "version": "8.5.2"
    },
    {
      "nodeId": 2,
      "host": "camunda-platform-test-zeebe-2.camunda-platform-test-zeebe.ck-test-helm.svc",
      "port": 26501,
      "partitions": [
        {
          "partitionId": 1,
          "role": "follower",
          "health": "healthy"
        },
        {
          "partitionId": 3,
          "role": "leader",
          "health": "healthy"
        },
        {
          "partitionId": 2,
          "role": "leader",
          "health": "healthy"
        }
      ],
      "version": "8.5.2"
    },
    {
      "nodeId": 1,
      "host": "camunda-platform-test-zeebe-1.camunda-platform-test-zeebe.ck-test-helm.svc",
      "port": 26501,
      "partitions": [
        {
          "partitionId": 1,
          "role": "follower",
          "health": "healthy"
        },
        {
          "partitionId": 3,
          "role": "follower",
          "health": "healthy"
        },
        {
          "partitionId": 2,
          "role": "follower",
          "health": "healthy"
        }
      ],
      "version": "8.5.2"
    }
  ],
  "clusterSize": 3,
  "partitionsCount": 3,
  "replicationFactor": 3,
  "gatewayVersion": "8.6.0-SNAPSHOT"
}
```

Also in the Zeebe gateway logs we can see that Operate was detected as new Member:

```
2024-06-14 11:28:47.279 [] [atomix-cluster-heartbeat-sender] [] INFO 
      io.atomix.cluster.protocol.swim - camunda-platform-test-zeebe-gateway-6d45d589db-9mml2 - Member added Member{id=camunda-platform-test-operate-57b4db4ff7-4sqj8, address=10.0.60.16:26502, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}

```

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/docs/contributing.md).

**Before opening the PR:**

- [ ] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/docs/contributing.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by Zelldon** [comment]
@aabouzaid is there a trick to correctly generate the golde-files for the alpha dir? 

```
$ make go.update-golden-only-lite 
\n[go.update-golden-only-lite] Chart dir: charts/camunda-platform-latest
?   	camunda-platform/test/unit/utils	[no test files]
ok  	camunda-platform/test/unit/camunda	62.667s
ok  	camunda-platform/test/unit/connectors	54.849s
ok  	camunda-platform/test/unit/console	56.084s
ok  	camunda-platform/test/unit/identity	54.559s
ok  	camunda-platform/test/unit/operate	55.162s
ok  	camunda-platform/test/unit/optimize	48.816s
ok  	camunda-platform/test/unit/tasklist	48.523s
ok  	camunda-platform/test/unit/web-modeler	83.065s
ok  	camunda-platform/test/unit/zeebe	54.578s
ok  	camunda-platform/test/unit/zeebe-gateway	54.962s
```

It checks the wrong dir. `make go.update-golden-only-lite camunda-platform-alpha` didn't work, maybe I miss something.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
@Zelldon All open 8.6 PRs have been merged, could you please rebase then we are ready to go :raised_hands:

**Comment by Zelldon** [comment]
@aabouzaid i rebased the pr. There are still some things failing it seems

**Review by aabouzaid — APPROVED** [review]
I've fixed a small issue with the linted files ... so we can merge :ok_hand:

**Pull request merged**
