### PR TITLE
Feat add nodeSelector/affinity/tolerations and podLabels for zeebe operate and tasklist

### PR DESCRIPTION
**Pull request by mihneastaub**
Added the following for zeebe `operate` and `tasklist` charts:
- `nodeSelector`, `affinity`, `tolerations`
- `podLabels`

related to https://github.com/camunda/camunda-platform-helm/pull/245

### CODE REVIEW

**Comment by Zelldon** [comment]
Hey @mihneastaub sorry for the late response! I was out of office. Currently we do a bigger refactoring, after that (begin of next week) I will take care of your PR and get this merged. Thanks for your contribution and that you added tests etc, I really appreciate this!

**Comment by mihneastaub** [comment]
Hello @Zelldon ! Thank you for the response, if you need help from my side please ping me.

**Comment by mihneastaub** [comment]
@Zelldon, the write looks very good! 

I have migrated my changes to the latest `main`.

**Review by Zelldon — APPROVED** [review]
Great! Thank you very much for your contribution :+1:

**Pull request merged**
