### PR TITLE
Release Camunda Platform Helm Chart v10.0.0

### PR DESCRIPTION
**Pull request by aabouzaid**
**Before opening the PR:**

- [x] Run `make release.chores`
- [x] Create a PR with the printed URL
- [x] [Trigger Renovate](https://developer.mend.io/github/camunda/camunda-platform-helm) to ensure that all deps are updated (to avoid any delayed sync from Renovate service).

**After opening the PR:**

- [x] Take a final look at the release commits (version bump and release notes)
- [x] Make sure that all checks in the PR passed
- [x] If everything in place, add `release` label to the PR
- [x] Follow up the release workflow and make sure it succeeded (double-check the [releases page](https://github.com/camunda/camunda-platform-helm/releases))
- [ ] Ensure that all fixed [issues with support label](https://github.com/camunda/camunda-platform-helm/issues?q=is%3Aissue+label%3Asupport+is%3Aclosed) has the release version like `version:10.0.0` (this will be automated later).

If the release is a minor version bump (e.g. from 8.2.x to 8.3.0):
- [x] Make sure the regression test matrix is updated: located at [.github/workflows/test-regression.yaml](https://github.com/camunda/camunda-platform-helm/blob/main/.github/workflows/test-regression.yaml#L33-L36)

### CODE REVIEW

**Comment by jessesimpson36** [comment]
`global.image.tag` in values-latest.yaml is still on version 8.4.6

**Comment by jessesimpson36** [comment]
The other versions look right to me.

**Comment by jessesimpson36** [comment]
I'm personally okay with values-latest.yaml being updated some time after this release is merged, so I'm going to approve the PR now.

**Comment by aabouzaid** [comment]
NOTE: Please use [v10.0.1](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-10.0.1).
And if you upgrading from v9.0.0, you still need to apply the upgrade guide for [v10,0.0](https://docs.camunda.io/docs/self-managed/setup/upgrade/#helm-chart-1000).

**Pull request merged**
