### PR TITLE
chore: generate markdown from values file

### PR DESCRIPTION
**Pull request by HamzaMasood1**
### Which problem does the PR fix?

Fixes: https://github.com/camunda/camunda-platform-helm/issues/401

Using the tool listed in the issue to generate README.md file from values.yaml
### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by HamzaMasood1** [comment]
I might take out all the @extra comments. I just added them in incase it looks better.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review that once all PRs related to v8.3 are merged.

**Comment by aabouzaid** [comment]
The generated file looks great :star_struck: 

Is there a mechanism to merge/append the generated content to the main README.md file? :thinking:

**Comment by HamzaMasood1** [comment]
> The generated file looks great 🤩
> 
> Is there a mechanism to merge/append the generated content to the main README.md file? 🤔

Yes there is : )
I run the following command: 
```bash
readme-generator --values values.yaml --readme README-gen.md
```

We can just use the correct README file when running the binary in the CI pipeline.

**Comment by aabouzaid** [comment]
> > The generated file looks great 🤩
> > Is there a mechanism to merge/append the generated content to the main README.md file? 🤔
> 
> Yes there is : ) I run the following command:
> 
> ```shell
> readme-generator --values values.yaml --readme README-gen.md
> ```
> 
> We can just use the correct README file when running the binary in the CI pipeline.

I think that will override the main README file.

What we need is to have a fixed section that's not auto-generated followed by the auto-generated markdown.

if the tool doesn't have it then it's just a matter of concatenating the 2 files on the fly.

**Comment by HamzaMasood1** [comment]
> > Yes there is : ) I run the following command:
> > ```shell
> > readme-generator --values values.yaml --readme README-gen.md
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can just use the correct README file when running the binary in the CI pipeline.
> 
> I think that will override the main README file.
> 
> What we need is to have a fixed section that's not auto-generated followed by the auto-generated markdown.
> 
> if the tool doesn't have it then it's just a matter of concatenating the 2 files on the fly.

There's no need to concatenate two files since the helm chart generator allows you to generate the output in a certain section fo the readme: https://github.com/bitnami-labs/readme-generator-for-helm#:~:text=The%20README.md%20file%20with%20a%20%23%23%20Parameters

**Review by aabouzaid — APPROVED** [review]

**Pull request merged**
