### PR TITLE
test: fix tgz issue in upgrade flow and some refactoring

### LINKED ISSUE #1622: [ISSUE] Chart upgrade fails due to *.tgz not evaluating to a real path
**Describe the issue:**

Recent change in the helm chart caused the upgrade CI to fail, since we now reference *.tgz, but earlier in the CI, where we run `helm pull` and `helm package`, we pull those into `TEST_TMP_DIR` or `/tmp`

https://github.com/camunda/camunda-platform-helm/actions/runs/8694679254/job/23844101939?pr=1619

**Actual behavior:**

**Expected behavior:**

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

### PR DESCRIPTION
**Pull request by jessesimpson36**
### Which problem does the PR fix?

I created this PR as a refactoring of our integration tests. Part 1 stopped working because github actions kept running an old version of the templates.

closes #1622 

This fixes the issue where we're looking for a tgz file when no tgz file exists due to the `--untar` flag supplied.

There  are also some other necessary refactorings Hamza and I did together  for us to understand what was the issue, and how to apply a fix without breaking something else.

Refactorings include:
- renaming some of the taskfile definitions to be more descriptive of what version of the chart it's installing
- renaming some of the environment variables to describe how they're being used
- moving the environment variables to primarily one file
- moving the upgrade commands to one file.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by jessesimpson36** [comment]
Upgrade test will not pass due to a bug in github actions where it's running the version of test-integration-template.yaml on main rather than the branch.

**Comment by jessesimpson36** [comment]
just rebased on main to get the latest patches which should help with some of the failing tests.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
@jessesimpson36 could you please create a task for this PR so it's easy to track and also update the PR details? (the description is out of date, and there are many conflicts)

**Comment by jessesimpson36** [comment]
Closing since this is quite out-of-date

**Pull request closed without merging**
