### PR TITLE
fix(8.5): revert "dropped namespace from zeebe advertisedHost and initialContactPoints"

### PR DESCRIPTION
**Pull request by jessesimpson36**
Corresponding Issue: #2216 

Related to this PR: #2170 

This reverts commit 564581d1f136f055a72975f362812b567937ccfc.

### Which problem does the PR fix?

This is a revert due to discovered issues when installing with multi-region

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/docs/contributing.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/docs/contributing.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by jessesimpson36** [comment]
@aabouzaid suggested keeping the DNS change inside the alpha version, and rely on 
https://github.com/camunda/c8-multi-region
to implement a fix on their end / put in our upgrade guide to make sure you add the advertisedHost variable if you are using multi-region.

I'm not sure if I agree, but my main concern right now is fixing the problem for 8.5.

**Comment by aabouzaid** [comment]
@jessesimpson36, we should not make behavior changes in the released charts unless it's mandatory (which it is not in this case).
So we can introduce this change in the Alpha since it's not released yet.

**Comment by maxdanilov** [comment]
@jessesimpson36 thank you for addressing it! do you know when will the `oci://ghcr.io/camunda/helm/camunda-platform:0.0.0-snapshot-alpha` release have it included?

**Comment by jessesimpson36** [comment]
My intention in reducing the scope of this PR for 8.5 was in hopes we could get an 8.5 release with the fix out sooner for customers with multiregion enabled.  Then we could go through rounds of discussing whether alpha should or should not have this reverted.  The latest thing Ahmed and I discussed was an alternative where we have logic like

```
            - name: ZEEBE_BROKER_NETWORK_ADVERTISEDHOST
              {{- if .Values.global.multiregion.enabled }}
              value: "$(K8S_NAME).$(K8S_SERVICE_NAME).$(K8S_NAMESPACE).svc"
              {{- else }}
              value: "$(K8S_NAME).$(K8S_SERVICE_NAME)"
              {{- end }}

```
And we think we can have  this functionality pretty quickly for both 8.5 and alpha. I think today or tomorrow would be a reasonable timeframe for a small change like this.

**Pull request merged**
