### PR TITLE
chore(tasklist): configure Tasklist's management port

### PR DESCRIPTION
**Pull request by houssain-barouni**
### What's in this PR?
same as https://github.com/camunda/camunda-platform-helm/pull/1660

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] In the repo's root dir, run `make go.update-golden-only`.
- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
Given these changes only in Camunda 8.6 alpha and we don't have an alpha chart yet, this PR is blocked until then.
We are almost there with the new structure and will have the chart for Camunda 8.6 alpha in the next 2 weeks.

**Comment by aabouzaid** [comment]
@houssain-barouni

The alpha chart is now available in the following path:
https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform-alpha

and alpha artifact is available with the fixed version `0.0.0-main-alpha` (by default using the latest alpha version of the apps):

```
helm template my-camunda-devel \
  oci://ghcr.io/camunda/helm/camunda-platform \
  --version 0.0.0-main-alpha
```

Please rebase and make the changes for 8.6 in the alpha dir (you will probably just copy-paste the changed files).

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review the PR once it's done.

**Comment by houssain-barouni** [comment]
> I will review the PR once it's done.

Changes are made, can you please review them?

**Review by aabouzaid — APPROVED** [review]
LGTM, thank you :+1:

**Pull request merged**
