### PR TITLE
fix:  fullUrl for identity

### PR DESCRIPTION
**Pull request by hamza-m-masood**
### What's in this PR?
related to: https://github.com/camunda/camunda-platform-helm/issues/1604 and https://github.com/camunda/camunda-platform-helm/issues/1589

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] Tests for charts are added (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by jessesimpson36** [comment]
theres logic here that might be impacted by this change:
https://github.com/camunda/camunda-platform-helm/blob/880bc8f0ae71ff9b06ba2dbae20fe4fe78cc312e/charts/camunda-platform/templates/identity/_helpers.tpl#L26-L43

**Comment by hamza-m-masood** [comment]
@jessesimpson36 
Thanks for pointing that out. I don't think inverting the conditions would work well because the fullURL will be ignored if ingress is enabled. That is not the case with the current logic. I can embed the localhost url directly in the template itself. I can try that out.

**Comment by hamza-m-masood** [comment]
@jessesimpson36 I took the localhost url out of the values.yaml and added it to the tpl file. What do you think? :)

**Comment by jessesimpson36** [comment]
Oh wow! brilliant! I think this will work

**Comment by jessesimpson36** [comment]
Unfortunately, I was not able to log in with the base helm chart and using only port-forwards. I still had to set `IDENTITY_URL` equal to `http://localhost:8080`.

we might be missing something else in the configuration that needs to be set to the same value.

**Comment by hamza-m-masood** [comment]
At least we don't the initial error when the pods start with the default values.yaml.

**Review by jessesimpson36 — APPROVED** [review]

**Pull request merged**
