### PR TITLE
docs: add details about c8 helm chart versioning

### PR DESCRIPTION
**Pull request by aabouzaid**
### What's in this PR?

Explicitly documenting the versioning schema used in the C8 Helm chart and how it could differ from [C8 apps](https://github.com/camunda/camunda-platform).

Fixes: [distribution #25](https://github.com/camunda/distribution/issues/25)

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [x] The main Helm chart and sub-chart are updated (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Review by menski — APPROVED** [review]
lgtm

**Comment by aabouzaid** [comment]
@christinaausley I appreciate your feedback about the wording.

**Review by christinaausley — APPROVED** [review]
Wording adjustments for clarity in my latest commit and technical review. Let me know if you have any questions about these 👍

**Comment by christinaausley** [comment]
@aabouzaid Can you let me know where I may have gone wrong here on the build? This is my first time contributing to this repo, so still learning the ropes.

**Comment by aabouzaid** [comment]
@christinaausley all good on your side, that's an issue in the repo pipeline.
Thanks for your help :rocket:

**Pull request merged**
