### PR TITLE
fix: use new disk usage configs for zeebe

### LINKED ISSUE #926: [ISSUE] Remove deprecated Zeebe disk watermarks
**Describe the issue:**

Zeebe charts are configured with the deprecated disk watermarks. by default.
https://github.com/camunda/camunda-platform-helm/blob/ed804194e653ef9e12ed963550250ca087e86049/charts/camunda-platform/values.yaml#L229-L232 

We should remove them and probably configure using the new ones https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/disk-space/

### PR DESCRIPTION
**Pull request by deepthidevaki**
### Which problem does the PR fix?

closes #926 

### What's in this PR?

Replace old deprecated Zeebe configs for disk usage with the new ones. The new config is documented in https://docs.camunda.io/docs/self-managed/zeebe-deployment/operations/disk-space/

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Review by megglos — APPROVED** [review]
👍 

@deepthidevaki these were introduced in 8.2, right?

@aabouzaid afaik for the helm chart there are not stable version branches maintained were we might need to merge that to?

**Comment by aabouzaid** [comment]
@megglos if that's something only for 8.3, then no more actions are needed.

If they should be backported, then that should also be added to the corresponding version file here:
https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform/values

just like that:

```
zeebe:
  env:
  - name: ZEEBE_BROKER_DATA_DISK_FREESPACE_REPLICATION
    value: "2GB"
  - name: ZEEBE_BROKER_DATA_DISK_FREESPACE_PROCESSING
    value: "3GB"
```

**Comment by deepthidevaki** [comment]
It must be added to 8.2 as well. But just adding the env vars won't work. We have to unset the old env vars. If the old ones are available, Zeebe uses that for backwards compatibility. So I will leave it as it is for 8.2.

**Comment by deepthidevaki** [comment]
Oh. Thanks @aabouzaid for the hint. I will open another PR for it.

**Comment by deepthidevaki** [comment]
@aabouzaid Setting to empty string does not work. Spring boot cannot parse empty string to a null value. It fails with `org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'zeebe.broker.data.disk-usage-command-watermark' to double`. So I will leave it as it is in 8.2.

**Comment by aabouzaid** [comment]
@deepthidevaki could it work if we used `NONE`?

**Pull request merged**
