### PR TITLE
Add default actuator endpoints - Tasklist

### PR DESCRIPTION
**Pull request by aleksander-dytko**
add loggers,usage-metrics,backup
according to https://github.com/camunda/tasklist/blob/708913dee39d4506d46d251e68888d1f2cd12dc3/webapp/src/main/java/io/camunda/tasklist/Application.java#L121-L121

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [x] The main Helm chart and sub-chart are updated (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
@aleksander-dytko Thanks for the PR :+1: 
Could you please update the golden files to make the tests pass?

```
make go.test-golden-updated
```

**Comment by aleksander-dytko** [comment]
@aabouzaid could you please help me with that? 

I run the command on the root folder and get:
image

**Comment by aabouzaid** [comment]
@aleksander-dytko I'm not sure what the issue is here. It could be the Go version on your machine or so.
So I just made the changes.

**Comment by aleksander-dytko** [comment]
Thanks @aabouzaid!

**Pull request merged**
