### PR TITLE
Allow to override repository and tag for curator image

### PR DESCRIPTION
**Pull request by harmjanblok**

### CODE REVIEW

**Review by Zelldon — CHANGES_REQUESTED** [review]
Thanks so much for your contribution @harmjanblok :bow: 

Please adjust your commit message and follow our commit guide lines :) https://github.com/camunda/camunda-cloud-helm/blob/main/CONTRIBUTING.md#commit-guidelines
So for example change your message to 

```
feat: introduce image values for retentionPolicy

Allows to override repository and tag for curator image
```

Please also add also the new configuration to the README here https://github.com/camunda/camunda-cloud-helm/blob/main/charts/ccsm-helm/README.md#ccsm This makes it possible also for new users to find such config easier :) 

Thanks again and feel free to raise any concerns you might have regarding this :)

**Comment by Zelldon** [comment]
Please see https://github.com/camunda/camunda-platform-helm/pull/234#issuecomment-1072253714

**Comment by Zelldon** [comment]
Thanks @harmjanblok please add also the values to the Readme as written above 

> Please also add also the new configuration to the README here https://github.com/camunda/camunda-cloud-helm/blob/main/charts/ccsm-helm/README.md#ccsm This makes it possible also for new users to find such config easier :)

**Comment by harmjanblok** [comment]
> Thanks @harmjanblok please add also the values to the Readme as written above
> 
> > Please also add also the new configuration to the README here https://github.com/camunda/camunda-cloud-helm/blob/main/charts/ccsm-helm/README.md#ccsm This makes it possible also for new users to find such config easier :)

Oh sorry missed that point, I've updated the PR with the README changes.

**Review by Zelldon — APPROVED** [review]
Awesome thanks so much @harmjanblok :medal_sports:

**Comment by Zelldon** [comment]
Part of https://github.com/camunda/camunda-platform-helm/releases/tag/ccsm-helm-0.0.26

**Pull request merged**
