### PR TITLE
feat(console-sm): integrate with identity

### PR DESCRIPTION
**Pull request by urbanisierung**
### Which problem does the PR fix?

- relates https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/1190
- replaces #894 

### What's in this PR?

- Use new console preset from Identity, add `KEYCLOAK_INIT_CONSOLE_ROOT_URL`
  - Identity preset: https://github.com/camunda-cloud/identity/pull/2123
- New environment variables for Console:
  - `IDENTITY_BASE`: identity base url, for preview stage it should be `https://gke-dev-console-sm-main.ci.distro.ultrawombat.com/auth`
  - `IDENTITY_REALM`: auth realm --> `camunda-platform`
  - `IDENTITY_AUDIENCE`: auth audience --> `console`
  - `IDENTITY_CLIENT_ID`: console client id --> `console`

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by ultraschuppi** [comment]
@aabouzaid i think the ball is in your field, right? don't think it makes sense to have @urbanisierung as an assignee here

image

**Comment by aabouzaid** [comment]
@ultraschuppi I've already informed @urbanisierung that I have a couple of other tasks, and I will work on this the first thing on Monday :raised_hands:

**Comment by ultraschuppi** [comment]
> @ultraschuppi I've already informed @urbanisierung that I have a couple of other tasks, and I will work on this the first thing on Monday 🙌

i am asking about the assignment of this PR not on the timeline

**Comment by aabouzaid** [comment]
@ultraschuppi Adam is the assignee since he did the work and created the PR.
I'm only reviewing this PR unless I need to make changes and contribute to the PR and that if needed happens after the review.

**Review by aabouzaid — APPROVED** [review]
@urbanisierung I did small fix, and the rest LGTM, thank you 👌

Regarding the upgrade failed jobs, it's expected because that feature wasn't in the previous version (we need to add upgrade migration steps, but it's not needed since console is not GA yet).

**Comment by aabouzaid** [comment]
Merged as nothing else needed (discussed with @urbanisierung).

**Pull request merged**
