### PR TITLE
fix: unify imagePullPolicy across components

### PR DESCRIPTION
**Pull request by margic**
added imagePullPolicy to tasklist, operate, optimize and identity and added tests

### Related issues
 #396 

### What's in this PR?
added global imagePullPolicy to templates to match zeebe and zeebegateway
added tests to all for testing override using global pullPolicy

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls)
      for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added.
- [x] The main Helm chart and sub-chart are updated (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
@margic, thanks for your contribution :rocket: 

As I see the docs are not marked in the checklist. Also, could you please add the tests to `identity` and `zeebe-gateway`?

**Comment by margic** [comment]
> @margic, thanks for your contribution 🚀
> 
> As I see the docs are not marked in the checklist. Also, could you please add the tests to `identity` and `zeebe-gateway`?

Will do.

**Comment by margic** [comment]
I added the missing tests.

The documentation already has a entry about global pullPolicy that is make correct after this pull request. No documentation update necessary.

**Review by aabouzaid — APPROVED** [review]
LGTM, thank you @margic :+1:

**Pull request merged**
