### PR TITLE
Create a Windows version of the Helm patch 

### PR DESCRIPTION
**Pull request by vincentgiraud**
### Which problem does the PR fix?

Create a Windows version of the patch.bat post renderer script for Open Shift https://github.com/camunda/camunda-platform-helm/issues/439

### What's in this PR?

A bat file runnable from Windows as :
`helm install test camunda/camunda-platform --skip-crds -f openshift.yaml -f openshift-patch.yaml -f values.yaml --post-renderer ./patch.bat`

### CODE REVIEW

**Comment by aabouzaid** [comment]
Is it expected to have `sed` in Windows? :thinking:

**Comment by vincentgiraud** [comment]
I should have mentionned I'm using gitbash on Windows, not PowerShell

**Comment by aabouzaid** [comment]
@vincentgiraud This one? https://gitforwindows.org/

**Comment by vincentgiraud** [comment]
If I recall correctly it was this one https://git-scm.com/download/win (git bash is part of it)

**Comment by aabouzaid** [comment]
@vincentgiraud we need to know for sure :sweat_smile: 
We need some docs in the readme and the script to make it easy to use that script (basically the prerequisite)

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will get back to this again when the script and readme are updated.

**Comment by jessesimpson36** [comment]
This PR has been open too long, and the script / readme have not been updated since the last review. Closing.

**Pull request closed without merging**
