### PR TITLE
ci: release chart snapshot from main branch

### PR DESCRIPTION
**Pull request by aabouzaid**
### Which problem does the PR fix?

Fixes: https://github.com/camunda/camunda-platform-helm/issues/1683

### What's in this PR?

Release Camunda Helm chart snapshot to GitHub package registry as an OCI.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by jessesimpson36** [comment]
According to this page:
we already have 27 downloads on that artifact
2024-04-26-083341_grim

**Review by jessesimpson36 — APPROVED** [review]
Code looks good. Just answer my questions on the PR and I'll approve.

**Review by jessesimpson36 — CHANGES_REQUESTED** [review]
Answer above questions

**Comment by aabouzaid** [comment]
> I'm assuming this is not using github pages, and is using a registry that github is providing. Is that right? Do you intend to migrate what already exists in github pages over to this new registry?

No plans for that yet.
We could think about it when we do the repo rename.

**Review by jessesimpson36 — APPROVED** [review]

**Pull request merged**
