### PR TITLE
fix: set the network host and port to the zeebeGateway config

### PR DESCRIPTION
**Pull request by hamza-m-masood**
### Which problem does the PR fix?

Related issue: https://github.com/camunda/camunda-platform-helm/issues/1659
### What's in this PR?

I'm adding back the network host and port to the zeebe gateway config, and taking out the env vars from the deployment.
### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] In the repo's root dir, run `make go.update-golden-only`.
- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by hamza-m-masood** [comment]
DO NOT MERGE
Wait for this PR in the zeebe repo to be merged first: https://github.com/camunda/camunda/pull/19132

**Comment by hamza-m-masood** [comment]
Removed the env var since this PR will fix the overwrite problems: https://github.com/camunda/camunda/pull/19228

**Comment by aabouzaid** [comment]
> @aabouzaid I want this change to be present only in 8.6 and not 8.5 So do I add this in the alpha folder right?

@hamza-m-masood Exactly.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review the changes one moved to the alpha chart.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
The golden files need to be updated

```
chartPath="charts/camunda-platform-alpha" make go.update-golden-only
```

**Comment by hamza-m-masood** [comment]
I remember running the golden files before committing... strange. I will try again

**Comment by hamza-m-masood** [comment]
The golden files in the alpha folder are not being updated when running `make go.update-golden-only
` I will investigate

**Comment by hamza-m-masood** [comment]
Ah thanks! I was not aware that you need to specify a variable now.

**Comment by aabouzaid** [comment]
@hamza-m-masood Try to rebase, we just fixed an issue that could be related to the failed upgrade.

**Comment by hamza-m-masood** [comment]
Seems like one pod from the zeebe brokers is failing to start in the alpha upgrade flow

**Comment by hamza-m-masood** [comment]
This part of the integration tests in the upgrade workflow is failing:
```
• Test core functionality of Camunda (./tests/overlay/testsuite-core.yaml)
 	• TEST-Generating-machine-to-machine-token
 		• Tasklist (range=0) FAIL
 		  Testcase "TEST - Generating machine-to-machine token", step #0-0: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 503 (testsuite-core.yaml:0)
 		• Operate (range=1) FAIL
 		  Testcase "TEST - Generating machine-to-machine token", step #0-1: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 503 (testsuite-core.yaml:0)
 		• Optimize (range=2) FAIL
 		  Testcase "TEST - Generating machine-to-machine token", step #0-2: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 503 (testsuite-core.yaml:0)
 		• Connectors (range=3) FAIL
 		  Testcase "TEST - Generating machine-to-machine token", step #0-3: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 503 (testsuite-core.yaml:0)
 	• helperVenomToken
 		• Get Venom token FAIL
 		  Testcase "helperVenomToken", step #0-0: Assertion "result.statuscode ShouldEqual 200" failed. expected: 200  got: 503 (testsuite-core.yaml:0)
 	• TEST-Interacting-with-Camunda-login-page
 		• Console (range=0) PASS
 		• Keycloak (range=1) FAIL
 		  It's a failure after 4 attempts
 		• Identity (range=2) FAIL
 		  It's a failure after 4 attempts
 		• Operate (range=3) PASS
 		• Optimize (range=4) PASS
 		• Tasklist (range=5) PASS
 		• WebModeler (range=6) PASS
 	• TEST-Interacting-with-Camunda-login-page-Connectors
 		• Check Inbound Connectors PASS
	  	  [info] = Request Method: {{ .value.method }}
```
I am trying to debug to see why it is failing.

**Comment by aabouzaid** [comment]
@hamza-m-masood I believe that the fix in Zeebe is not in [Alpha3](https://github.com/camunda/camunda/releases/tag/8.6.0-alpha3).

**Comment by hamza-m-masood** [comment]
> I believe that the fix in Zeebe is not in [Alpha3](https://github.com/camunda/camunda/releases/tag/8.6.0-alpha3).

@aabouzaid Then I am confused on whyi it would work for the main integration flow and not the upgrade.

**Comment by hamza-m-masood** [comment]
@aabouzaid 
The upgrade flow is working. I am happy for this to be merged. Is this okay with you?

**Comment by hamza-m-masood** [comment]
Just realized that the history for this Pr is broken. I'll get it fixed.

**Comment by aabouzaid** [comment]
@hamza-m-masood, could you please rebase the changes on the `main` branch?

**Review by aabouzaid — CHANGES_REQUESTED** [review]
@hamza-m-masood, could you please rebase the changes on the `main` branch?

**Review by aabouzaid — APPROVED** [review]
LGTM, thank you :+1:

**Pull request merged**
