### PR TITLE
fix: application configurations for Operate + Tasklist

### PR DESCRIPTION
**Pull request by Zelldon**
### Which problem does the PR fix?

The Operate and Tasklist application file has been renamed on the way to a single application. It is now called `application.yaml`, instead of `application.yml`.

If we still use the old name, we would create a separate file and
not overwrite the existing one. This causes Spring to load multiple configs,
Spring will handle them in a way that the `yaml` overrides several configs
from the `yml` file.

See related investigation for more details https://github.com/camunda/camunda/issues/21033#issuecomment-2288476572

This causes the application to load defaults unexpectedly, like URL to ES will be
localhost:9200, that of course doesn't work in the K8 environment.

### What's in this PR?

In this PR I change the file names to the new expected names. This will override the default application.yaml files.

> [!NOTE]
> As the helm charts are overriding default application files (happened already since a while), this needs to be done carefully. We might want to think about a different approach, as application teams might add specific values in the `application.yaml` files as defaults which are then simply overridden. 

closes https://github.com/camunda/camunda/issues/21033

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/docs/contributing.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/docs/contributing.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by houssain-barouni** [comment]
Hello @Zelldon, these changes are already present in the alpha chart https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform-alpha

8.6 is meant to be run with the alpha chart (that will be released as 11.X.X)
I wonder if https://github.com/zeebe-io/benchmark-helm/blob/main/charts/zeebe-benchmark/Chart.yaml can use a non-released chart ?

**Comment by Zelldon** [comment]
🤯 


Thanks @houssain-barouni i missed that. I remember you and roman did something on the charts but i guess i get also confused with the latest charts as it is not part of it their.

Do you know whether the alpha charts are released? Only then we could use them. 🤔

**Comment by houssain-barouni** [comment]
> 🤯
> 
> Thanks @houssain-barouni i missed that. I remember you and roman did something on the charts but i guess i get also confused with the latest charts as it is not part of it their.
> 
> Do you know whether the alpha charts are released? Only then we could use them. 🤔

No, AFAIK they are not released. 
During the next minor release (October) the alpha chart will become the latest and will be released as 11.0.0. (@aabouzaid please correct me if I am mistaken) 
If your changes are backward compatible with 8.5, we can apply them on the latest charts as well. 
The next scheduled release will be in one month, so maybe we can just wait for the minor release in October ;) 

Alternatively, we can make https://github.com/zeebe-io/benchmark-helm/blob/main/charts/zeebe-benchmark/ pull the alpha chart an install it as a local chart (like we do in the helm charta integration tests), this would help solving similar future issue.

**Comment by aabouzaid** [comment]
Alpha charts are available but in a different [Helm repo](https://github.com/camunda/camunda-platform-helm/pkgs/container/helm%2Fcamunda-platform).

You can use the alpha using:
- Versioned: ghcr.io/camunda/helm/camunda-platform:0.0.0-8.6.0-alpha4
- Snapshot: ghcr.io/camunda/helm/camunda-platform:0.0.0-snapshot-alpha

**Comment by Zelldon** [comment]
Sorry for the noise :) i will try tomorrow with the alpha version 👍

**Comment by Zelldon** [comment]
> * 0.0.0-8.6.0-alpha4

@aabouzaid do you have an index.yaml which I can reference in the Chart.yaml? 🤔

**Comment by Zelldon** [comment]
Tried as normal repo, which obviously failed but [with OCI ](https://helm.sh/docs/topics/registries/#specifying-dependencies)it works 🚀 


```

  - name: camunda-platform
    repository: "oci://ghcr.io/camunda/helm"
    version: "0.0.0-8.6.0-alpha4"
    condition: "camunda.enabled"
```

🚀

**Pull request closed without merging**
