### PR TITLE
Adding linting to helm charts

### PR DESCRIPTION
**Pull request by HamzaMasood1**
### Which problem does the PR fix?

https://github.com/camunda/camunda-platform-helm/issues/415
### What's in this PR?

An attempt to lint and standardize all of our helm charts.
### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by HamzaMasood1** [comment]
I am noticing a lot of style inconsistencies on the pre-rendered helm charts as well, but unfortunately we won't be able to lint them in this PR.

**Comment by HamzaMasood1** [comment]
I have the following issue in the zeebe and zeebe-gateway golden file:

```yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/component
          operator: In
          values:
          - zeebe-gateway
      topologyKey: kubernetes.io/hostname
```

As you can see the `- labelSelector` is not indented. I tried modifying the helm template manifest in both zeebe and zeebe-gateway in order to get the indentation working, but was not able to. Any help on this would be appreciated.

**Comment by HamzaMasood1** [comment]
I would like feedback on the yamllint config. It can be found in the config section within the .github folder.

**Review by drodriguez-305 — APPROVED** [review]
Approving now and we will fix any issues presented after merge if anything.

**Pull request merged**
