### PR TITLE
Kubernetes API: upgrade from policy/v1beta1 to policy/v1

### PR DESCRIPTION
**Pull request by AndersRunningen**
### Which problem does the PR fix?

https://github.com/camunda/camunda-platform-helm/issues/498

### What's in this PR?

Trying to fix outdated API-versions in:
- `PodDisruptionBudgets` from `policy/v1beta1` to `policy/v1`
-  `CronJobs` from `policy/v1beta1` to `policy/v1`

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [x] The main Helm chart and sub-chart are updated (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### To-Do

- [ ] Update helmchart version, a bit uncertain where you would like these changes
- [x] Tested `helm install camunda .` in AKS cluster running kubernetes 1.25.4, everything started as before

### CODE REVIEW

**Comment by aabouzaid** [comment]
@AndersRunningen thanks for your contribution :rocket: 

I've tested your changes, and everything looks good.
So please remove my commit and push again and I will merge it.

Regarding this:
> Update helmchart version, a bit uncertain where you would like these changes

no action is needed from your side, I will do that in the next release.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will merge it once my commit is removed.

**Comment by AndersRunningen** [comment]
@aabouzaid Thank you for doing additional tests 👏  Reverted the commit you had and pushed the changes. Everything should be ok from my perspective now 👍

**Comment by aabouzaid** [comment]
@AndersRunningen Actually I find it's a good idea to enable the disabled config so we can see them in action (I've tested it and it looks good and doesn't delay the tests).

Thanks for your contribution :rocket:

**Comment by MennaKhaled** [comment]
This is holding us back as well. Cronjobs disabled for now which is a big hassle.

**Comment by aabouzaid** [comment]
@MennaKhaled v8.1.6 is out now.

**Pull request merged**
