### PR TITLE
feat: warning and error for not setting existingSecrets for all components

### LINKED ISSUE #1868: [TASK] Create deprecation warning for mandating existingSecrets (removes need for secrets extraction during upgrade)
## Related to

https://github.com/camunda/distribution/issues/125

Epic: 
https://github.com/camunda/product-hub/issues/1957

## Overview

As part of the Epic to improve the upgrade experience, we believe upgrading will be simpler by removing the auto-generation of passwords, and instead move to specifying the passwords in Secrets.

This task is to create a constraint with a few different modes:
1. Deprecation warning:  some sort of alert that will inform the user that in the next minor version, an error will appear if you do not specify existingSecrets for all passwords
2. Deprecation error: if existingSecrets are not present, prevent the installation from finishing.

### PR DESCRIPTION
**Pull request by jessesimpson36**
### Which problem does the PR fix?

closes #1868 

This will prevent the need for the [Secrets Extraction](https://docs.camunda.io/docs/next/self-managed/setup/upgrade/#secrets-extraction)  steps when performing an upgrade of the camunda helm chart, by requiring secrets be applied before installation or upgrade.

### What's in this PR?

This PR comes with a constraint which will mandate that all `existingSecrets` are set.  This PR also introduces a feature flag under 
```
global:
  testDeprecationFlags:
    existingSecretsMustBeSet: "warning"
```
The two possible values are "warning" and "error".   This is done for the purposes of testing the behavior in warning-mode (continue with install but display warning after installation)  vs error-mode (fail and halt installation). In the final draft of this PR, I hope this idea of feature flags can remain so that testing can occur on each mode prior to the code being activated in a release.

however, when it's time to switch this feature into error mode, we can remove the `existingSecretsMustBeSet` key from `testDeprecationFlags` and hard-code the conditional pathway to `true` (or something equivalent).

I've also included unit tests for a few small scenarios:
1. Test that the error message displays
2. Test that the error message does not complain about components that are disabled
3. Test that the error message does not complain about components with the `existingSecret` set.
4. Test that the warning mode does not prevent installation.

When the error message displays, the following text will appear:

```
[camunda][error]
As of appVersion 8.7, the camunda helm chart will NOT perform automatic passwords generation.
This means that secrets must be provided in the form of kubernetes secrets.

An example of one of these secrets is:

apiVersion: v1
kind: Secret
metadata:
  name: identity-secret-for-components
type: Opaque
data:
  operate-secret: <base64-encoded-secret>
  tasklist-secret: <base64-encoded-secret>
  optimize-secret: <base64-encoded-secret>
  connectors-secret: <base64-encoded-secret>
  console-secret: <base64-encoded-secret>
  keycloak-secret: <base64-encoded-secret>
  zeebe-secret: <base64-encoded-secret>
  admin-password: <base64-encoded-secret> # used for keycloak
  management-password: <base64-encoded-secret> # used for keycloak
  postgres-password: <base64-encoded-secret> # used for postgresql admin password
  password: <base64-encoded-secret> # used for postgresql user password

The following values inside your values.yaml need to be set but were not:
       
 global.identity.auth.connectors.existingSecret 
 global.identity.auth.identity.existingSecret 
 global.identity.auth.operate.existingSecret 
 global.identity.auth.tasklist.existingSecret 
 global.identity.auth.optimize.existingSecret 
 global.identity.auth.console.existingSecret 
 global.identity.auth.zeebe.existingSecret 
 identityKeycloak.auth.existingSecret 
 identityKeycloak.postgresql.auth.existingSecret 
 postgresql.auth.existingSecret 
 identityPostgresql.auth.existingSecret

Use --debug flag to render out invalid YAML
```

This branch is based off of https://github.com/camunda/camunda-platform-helm/pull/1840 because that feature branch introduces a couple more `existingSecret` options to webModeler components, and is mostly ready for merge.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by hamza-m-masood** [comment]
Is this ready for review? The PR is still in draft state.

**Comment by jessesimpson36** [comment]
Yeah it's ready for review.   I was just looking into the lint-and-test errors, which it seems is because of the pull_request_target stuff.

**Comment by hamza-m-masood** [comment]
@jessesimpson36  Maybe my [PR](https://github.com/camunda/camunda-platform-helm/pull/1875) can be merged first so you can continue testing on this PR.

**Review by drodriguez-305 — APPROVED** [review]
Looks good just the readme errors for those are we manually updating them?

`ERROR: Missing metadata for key: global.testDeprecationFlags.existingSecretsMustBeSet`

**Pull request merged**
