### PR TITLE
ci: re-enable service monitor tests

### PR DESCRIPTION
**Pull request by jessesimpson36**
### Which problem does the PR fix?

The problem with our prometheus deployment is now resolved, and it should now be safe to re-enable the tests. For more details about what was wrong in our deployment, look here: https://github.com/camunda/distribution/pull/100

Related to https://github.com/camunda/camunda-platform-helm/issues/733

### What's in this PR?

Just uncommenting a test that was previously disabled.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [x] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
I just realized that our main workflow was affected by a bug in GHA where in the `pull_request_target` workflow traits the bool input as a string but in `workflow_call` it treats them as a bool, So the tests actually skipped as shown here:

https://github.com/camunda/camunda-platform-helm/actions/runs/7089075156/job/19294004602?pr=1107

I've fixed the issue in the main branch (pr no. #1109), so please rebase to run the integration tests and see the changes.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review it again after the suggested change.

**Comment by jessesimpson36** [comment]
I'm confused. I rebased, but the builds aren't starting.  Perhaps the PR needs to be closed and re-created to actually process the changes after rebasing on latest main? in the "checks" I see

```
[Test - Integration: .github#L1](https://github.com/camunda/camunda-platform-helm/pull/1107/files#annotation_16157304090)
Canceling since a deadlock for concurrency group 'Test - Integration-1107' was detected between 'top level workflow' and 'test'
```

**Comment by aabouzaid** [comment]
@jessesimpson36 we had the concurrency for the caller workflow and template workflow (the template) with the same key, which made that deadlock (each one cancels the other in a loop). I've fixed it already, and it should work fine now.

**Review by aabouzaid — APPROVED** [review]
All works as expected, thank you :+1:

**Pull request merged**
