### PR TITLE
feat: zeebe gateway authentication

### PR DESCRIPTION
**Pull request by megglos**
### Which problem does the PR fix?

Adds zeebe gateway authentication setup #608

### What's in this PR?

Sets up zeebe gatwway authentication as well as a default client to be used by operate, tasklist & connectors.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [x] The main Helm chart and sub-chart are updated (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
@megglos I'm looking into it now :+1:

**Comment by aabouzaid** [comment]
Something is odd, after enabling the auth, the tests became super flaky.
I'm trying to understand what's going on here :thinking:

**Comment by aabouzaid** [comment]
the issue has nothing to do with the auth, it's about the CI infra where we are using the spot (preemptable) instances and they are not stable by design.

**Comment by nhoangduy1912** [comment]
@aabouzaid How do I disable zeebe gateway authentication?

**Comment by aabouzaid** [comment]
@nhoangduy1912 either in the app config or via env vars.

In the env vars, you need to set:

```
zeebe-gateway:
  env:
  - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
    value: "none"
```

**Comment by AndersRunningen** [comment]
@aabouzaid When testing this in a upgrade from 8.1.15 to 8.2.12 we are seeing that the value `ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE` is not set to "none" when using the method above. From what we can see this is already set as an environment variabel in the Helmchart and overruled by the configured value?

If I manually edit the deployment and set the env variable to "none" it works as expected. 

In regards to the [documentation](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-config/#zeebegatewayclustersecurityauthentication) of Zeebe-Gateway it is the right place to add the env, but since the value is already hardcoded in the helmchart, it doesn't add the new value in the helm install command? You might have some ideas on how to solve this as well?

**Comment by aabouzaid** [comment]
@AndersRunningen the extra vars provided in the values file has higher priority over what's pre-defined in the manifest template.

that means if you set it as above, you will see in the deployment 2 ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE, but the last one is the active (you can check it the pod by `echo $ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE` to see the active value).

**Pull request merged**
