### PR TITLE
feat(zeebe-gateway): update identity configuration env vars

### LINKED ISSUE #1105: [TASK] Replace Identity vars with generic OICD vars
**Related to:**

* Epic issue: https://github.com/camunda-cloud/identity/issues/2162
* Zeebe issue: https://github.com/camunda/zeebe/issues/15389

**Overview:**

Zeebe now integrates the `identity-spring-boot-autoconfig` dependency which can pick up Identity-specific configuration properties directly, and pass them to the Zeebe Gateway. 

**Actions:**

- [x] Replace the Zeebe configuration vars related to Identity (documented [here](https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/gateway-config/#zeebegatewayclustersecurityauthenticationidentity)), with the dedicated Camunda Identity properties (documented [here](https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/)).
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1155
- [ ] https://github.com/camunda/camunda-platform-helm/pull/1122
```

### PR DESCRIPTION
**Pull request by koevskinikola**
### Which problem does the PR fix?

Zeebe now integrates with the identity-spring-boot-autoconfiguration module which picks up Camunda Identity configuration properties directly. This decouples the Camunda Identity configuration from Zeebe.

closes #1105

### What's in this PR?

* The PR replaces Zeebe config vars with Identity config vars. 
* The PR updates the `.golden` file related to the changes in the template.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review it again after the suggested change.

**Comment by koevskinikola** [comment]
@Ben-Sheppard just an FYI to confirm that the env vars I updated are the correct ones in this PR.

**Comment by koevskinikola** [comment]
@aabouzaid I applied the changes.

**Review by Ben-Sheppard — APPROVED** [review]
The vars look correct to me :)

**Comment by aabouzaid** [comment]
@Ben-Sheppard that change is meant for 8.4 or 8.3? :thinking:

**Comment by Ben-Sheppard** [comment]
8.4 @aabouzaid

**Comment by aabouzaid** [comment]
Thanks Ben for the info.

@koevskinikola for that case, we need to test that with the latest Identity alpha.
When it's released, please set the image tag under `identity.image.tag` in the values file so we ensure it's ready for merge.

And I will add it to the Helm chart 8.4 checklist afterward.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I've changed the PR to a draft to avoid any accidental merge.

**Comment by koevskinikola** [comment]
@aabouzaid I've applied your feedback. Let me know if anything else needs to be done to get this PR review-ready.

**Comment by aabouzaid** [comment]
@koevskinikola I tried to change Operate and Tasklist since they were failing.
But I'd say let's wait for all 8.4.0-alpha2 to be released next week, then test again to avoid all that hassle.

**Comment by Ben-Sheppard** [comment]
@aabouzaid - I've had to include some changes related to this PR in another PR of mine (to introduce OIDC support into the helm charts) https://github.com/camunda/camunda-platform-helm/pull/1155 does it make sense to centralise the effort?

**Comment by aabouzaid** [comment]
@Ben-Sheppard I'd say let's keep them separated.
Do we have any dependency between this PR and PR no. #1155? :thinking:

**Comment by Ben-Sheppard** [comment]
We do in the way that both PRs touch the same config :)

**Comment by aabouzaid** [comment]
@Ben-Sheppard, in that case, let's close this PR and work on your new one since it has the new vars for all components :+1:

**Pull request closed without merging**
