### PR TITLE
refactor: configure Operate's management port

### PR DESCRIPTION
**Pull request by romansmirnov**
### Which problem does the PR fix?

https://github.com/camunda/camunda-platform-helm/issues/1661

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] In the repo's root dir, run `make go.update-golden-only`.
- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
Given these changes only in Camunda 8.6 alpha and we don't have an alpha chart yet, this PR is blocked until then.
We are almost there with the new structure and will have the chart for Camunda 8.6 alpha in the next 2 weeks.

**Comment by Langleu** [comment]
@aabouzaid but isn't the main branch the "8.6" branch in a sense or do you collect all 8.6 changes till 8.6?
Snapshot tests have been failing for a week because of this missing change.

**Comment by aabouzaid** [comment]
@Langleu nope, the main chart is for the latest stable version (8.5) where we could add non-breaking features in addition to the patches.

we never had `next` which represents alpha and it (alpha version) probably worked in the past with the main branch because we didn't have big changes between minors.

for that reason, we will have a chart in the path `camunda-platform-alpha` which accumulates all changes for the next version.

**Comment by Langleu** [comment]
thanks for the info 👍, looking forward!

**Comment by maxdanilov** [comment]
> for that reason, we will have a chart in the path camunda-platform-alpha which accumulates all changes for the next version.

@aabouzaid do you know when we can expect this? until then, the Helm chat snapshots provide not much value for the internal tests.

**Comment by mschoe** [comment]
As we are getting closer to the alpha3 release this is causing delays with testing new features in the SM environment. Currently we cannot execute automated and manual testing against SM. 
@aabouzaid do you have a timeline when the PR get merged?

**Comment by maxdanilov** [comment]
Same for the InfraEx team with the nightly tests, the Helm snapshots are not feasible to be used without this fix.

**Comment by aabouzaid** [comment]
@romansmirnov @maxdanilov @mschoe 

The alpha chart is now available in the following path:
https://github.com/camunda/camunda-platform-helm/tree/main/charts/camunda-platform-alpha

and alpha artifact is available with the fixed version `0.0.0-main-alpha` (by default using the latest alpha version of the apps):

```
helm template my-camunda-devel \
  oci://ghcr.io/camunda/helm/camunda-platform \
  --version 0.0.0-main-alpha
```

@romansmirnov please rebase and make the changes for 8.6 in the alpha dir (you will probably just copy-paste the changed files).

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review the PR once it's done.

**Review by aabouzaid — APPROVED** [review]
LGTM, thank you :+1:

**Pull request merged**
