### PR TITLE
fix: enable secrets deprecation flag in alpha by default

### PR DESCRIPTION
**Pull request by jessesimpson36**
### Which problem does the PR fix?

closes https://github.com/camunda/distribution/issues/275

related to #1868 

### What's in this PR?

In alpha, set deprecation feature flag to "warning".

edit:  I've also adjusted the alpha integration test so that the warning does not display.  it will now set all of the existingSecrets for each component.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/docs/contributing.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [ ] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/docs/contributing.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by jessesimpson36** [comment]
looks like there were some variables inside the common test folder expecting  the pre-generated secrets name for all charts, so my most recent commit backports this change to other releases.  all integration tests now  make use of existingSecret options in all stable versions.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
LGTM, thank you :+1:

Just one thing here is to leave the key `test.integration` and its auto-generated secret because the services are exposed to the internet and without it, a fixed secret will be used.

**Comment by jessesimpson36** [comment]
That is intentional. If I left the `test.integration` key in then the "upgrade" integration tests would fail since the old secret and the new secret have different names.  I would suggest implementing password rotation in the distribution repo level as opposed to having that secret be part of the chart. 

Does that sound reasonable, or would you still prefer it part of the chart?

**Comment by aabouzaid** [comment]
That should be fine for now, given we plan to provide auto-generation for secret object as in https://github.com/camunda/camunda-platform-helm/issues/1983

**Review by aabouzaid — APPROVED** [review]

**Pull request merged**
