### PR TITLE
refactor: in web-modeler switch to spring env vars for db config

### PR DESCRIPTION
**Pull request by wollefitz**
### What's in this PR?

Uses the environment variables recommended by https://docs.camunda.io/docs/self-managed/modeler/web-modeler/configuration/#database for configuring database connectivity.

Relates to https://github.com/camunda/web-modeler/issues/4457

### Hints 

https://github.com/camunda/camunda-platform-docs/pull/2243 adjusts the documentation after this PR was merged

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [x] Tests for charts are added (if needed).
- [x] The main Helm chart and sub-chart are updated (if needed).
- [x] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [x] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [x] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by aabouzaid** [comment]
@wollefitz thanks for the PR :bow: 

Please note that this is a breaking change (it will not work if someone uses the old syntax).

So we have 2 options:
1. Create a [helper](https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/templates/_helpers.tpl) to handle the old syntax and reformat it if it's set.
2. Wait till the next minor version and introduce it (8.3. which is in October).

**Comment by wollefitz** [comment]
Let's go for option 2 then and wait for the next minor release. The change is not important enough to invest additional time in creating a helper.

**Comment by aabouzaid** [comment]
⚠ Reminder, when squashing this PR in GH UI, ensure adding `BREAKING CHANGE` as the first line in the commit body.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
just adding this comment to stop the notifications for this pr :D

**Comment by aabouzaid** [comment]
@wollefitz since we are approaching the v8.3 release, could you please rebase on the main branch?

**Comment by wollefitz** [comment]
> @wollefitz since we are approaching the v8.3 release, could you please rebase on the main branch?

@aabouzaid Done ✅

**Review by aabouzaid — APPROVED** [review]

**Comment by aabouzaid** [comment]
@wollefitz Thanks for your effort :bow:

**Pull request merged**
