### PR TITLE
feat(connectors): add `initContainers` support

### PR DESCRIPTION
**Pull request by igpetrov**
### Which problem does the PR fix?

Add `initContainers` support to Connectors as per FR https://github.com/camunda/team-connectors/issues/496.

### What's in this PR?

Just adding additional option to add `initContainers`.

### Testing done

via `helm template ./charts/camunda-platform --debug`

```
# Source: camunda-platform/templates/connectors/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-connectors
  labels:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: camunda-platform
    helm.sh/chart: camunda-platform-8.2.13
    app.kubernetes.io/version: "8.2.13"
    app.kubernetes.io/component: connectors
  annotations:
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-platform
      app.kubernetes.io/name: camunda-platform
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: camunda-platform
      app.kubernetes.io/component: connectors
  template:
    metadata:
      labels:
        app: camunda-platform
        app.kubernetes.io/name: camunda-platform
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: camunda-platform
        helm.sh/chart: camunda-platform-8.2.13
        app.kubernetes.io/version: "8.2.13"
        app.kubernetes.io/component: connectors
    spec:
      imagePullSecrets:
        []
      containers:
        - name: connectors
          image: camunda/connectors-bundle:0.23.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL
              value: http://release-name-keycloak:80
            - name: CAMUNDA_OPERATE_CLIENT_CLIENT-ID
              value: connectors
            - name: CAMUNDA_OPERATE_CLIENT_CLIENT-SECRET
              valueFrom:
                secretKeyRef:
                  name: "release-name-connectors-identity-secret"
                  key: connectors-secret
            - name: CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM
              value: camunda-platform
            - name: CAMUNDA_OPERATE_CLIENT_URL
              value: "http://release-name-operate:80"
            - name: ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS
              value: "release-name-zeebe-gateway:26500"
            - name: ZEEBE_CLIENT_SECURITY_PLAINTEXT
              value: "true"
            - name: ZEEBE_CLIENT_ID
              value: zeebe
            - name: ZEEBE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "release-name-zeebe-identity-secret"
                  key: zeebe-secret
            - name: ZEEBE_AUTHORIZATION_SERVER_URL
              value: "http://release-name-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token"
            - name: ZEEBE_TOKEN_AUDIENCE
              value: zeebe-api
          command: []
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 1
      initContainers:
        - command:
          - wget
          - -O
          - /work-dir/index.html
          - http://info.cern.ch
          image: busybox:1.28
          name: install
          volumeMounts:
          - mountPath: /work-dir
            name: workdir
---
```

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added (if needed).
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Comment by igpetrov** [comment]
Hi @aabouzaid 
This one is ready to merge, could you please review?

**Review by sbuettner — APPROVED** [review]

**Comment by aabouzaid** [comment]
Looks like we have PRs that were opened at the same time.
@HamzaMasood1 is working on this topic in #885

@igpetrov could you please align with Hamza in the other PR since it's for all components?

**Comment by igpetrov** [comment]
Hi @aabouzaid good timing :)

We agreed with @HamzaMasood1 that he will move this code into his PR and we will close this one.

**Comment by aabouzaid** [comment]
@igpetrov thanks for the info :bow: 
I'm closing this PR according to that since the other PR is already merged :ok_hand:

**Comment by igpetrov** [comment]
Thanks a lot!

**Pull request closed without merging**
