### PR TITLE
Enable Identity for the Zeebe REST API

### LINKED ISSUE #1493: [TASK] Enable Identity authentication for the Zeebe REST API
**Related to:**

camunda/zeebe#16167

**Overview:**

In order to support multi tenancy with the REST API, we need to enable Identity authentication via the REST API in Zeebe.

**Actions:**

- [x] Activate the `identity-auth` profile when Identity is enabled for Zeebe via `SPRING_PROFILES_ACTIVE`

### PR DESCRIPTION
**Pull request by npepinpe**
### Which problem does the PR fix?

This PR adds support for Identity authentication (and thus multi-tenancy) for the Zeebe REST API when enabled.

closes #1493

### What's in this PR?

No new values are introduced, we just add the necessary environment variables to Zeebe. No specific design considerations either, it was a fairly small change.

Note that I didn't add integration tests as I still don't fully understand how these are set up and work.

### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [x] In the repo's root dir, run `make go.update-golden-only`.
- [x] There is no other open [pull request](../pulls) for the same update/change.
- [x] Tests for charts are added (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

<!--
### To-Do

- [ ] Possibly update the existing Identity integration tests?

### CODE REVIEW

**Comment by npepinpe** [comment]
Note that this feature does not work with 8.5.0-alpha2, as this relies on stuff we merged later on.

**Comment by npepinpe** [comment]
Tested with a token, everything works as expected :)

**Review by aabouzaid — APPROVED** [review]
LGTM :+1:
just waiting for the RC2 image release.

**Comment by megglos** [comment]
@aabouzaid the 8.5.0-RC2 image is available

**Pull request merged**
